// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/config.dart';
import 'api/cuda.dart';
import 'api/input.dart';
import 'api/instance.dart';
import 'api/orchestrator.dart';
import 'api/overlay.dart';
import 'api/simple.dart';
import 'api/theme.dart';
import 'api/transcription.dart';
import 'api/winprobe.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2005590586;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_inputvoice',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiInstanceAcquireSingleInstance();

  Future<void> crateApiOverlayApplyOverlayStyles({required String windowTitle});

  Future<void> crateApiInputAudioPrewarm();

  Future<void> crateApiInputAudioStartCapture();

  Future<String> crateApiInputAudioStopCaptureAndTranscribe({
    required TranscriptionLanguage lang,
  });

  Future<BigInt> crateApiInputAudioStopCaptureLen();

  Future<void> crateApiInputClearLastTranscription();

  Future<bool> crateApiCudaCudaAvailable();

  Future<int> crateApiWinprobeCurrentThreadId();

  Future<void> crateApiOverlayDisableMenuMode({
    required String windowTitle,
    required bool hide_,
  });

  Future<void> crateApiOverlayEnableMenuMode({required String windowTitle});

  Future<bool> crateApiTranscriptionEngineIsReady();

  Future<TranscriptionLanguage> crateApiTranscriptionGetLanguage();

  Future<String?> crateApiInputGetLastTranscription();

  Future<bool> crateApiThemeGetTaskbarLightTheme();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiOverlayHideOverlay({required String windowTitle});

  void crateApiSimpleInit();

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiTranscriptionInitEngine({required bool fullVerify});

  Future<InjectionOutcomeDto> crateApiInputInjectText({required String text});

  Future<AppConfigDto> crateApiConfigLoadConfig();

  Future<void> crateApiConfigSaveConfig({required AppConfigDto cfg});

  Future<void> crateApiTranscriptionSetLanguage({
    required TranscriptionLanguage lang,
  });

  Future<void> crateApiOverlayShowOverlayNoActivate({
    required String windowTitle,
  });

  Stream<HotkeyEventDto> crateApiInputStartHotkeyMonitor();

  Stream<UiStateDto> crateApiOrchestratorStartOrchestrator();

  Future<void> crateApiInputStopHotkeyMonitor();

  Future<void> crateApiOrchestratorStopOrchestrator();

  Future<void> crateApiThemeStopTaskbarThemeWatcher();

  Future<String> crateApiTranscriptionTranscribePcm({
    required List<int> pcm,
    required TranscriptionLanguage lang,
  });

  Future<void> crateApiConfigUpdateLanguage({required String lang});

  Future<void> crateApiConfigUpdateModelVerified({required bool verified});

  Future<void> crateApiConfigUpdatePaused({required bool paused});

  Future<void> crateApiConfigUpdateUiLanguage({required String lang});

  Future<String> crateApiTranscriptionVerifyModel();

  Stream<bool> crateApiThemeWatchTaskbarTheme();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiInstanceAcquireSingleInstance() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInstanceAcquireSingleInstanceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInstanceAcquireSingleInstanceConstMeta =>
      const TaskConstMeta(debugName: "acquire_single_instance", argNames: []);

  @override
  Future<void> crateApiOverlayApplyOverlayStyles({
    required String windowTitle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(windowTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiOverlayApplyOverlayStylesConstMeta,
        argValues: [windowTitle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOverlayApplyOverlayStylesConstMeta =>
      const TaskConstMeta(
        debugName: "apply_overlay_styles",
        argNames: ["windowTitle"],
      );

  @override
  Future<void> crateApiInputAudioPrewarm() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiInputAudioPrewarmConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputAudioPrewarmConstMeta =>
      const TaskConstMeta(debugName: "audio_prewarm", argNames: []);

  @override
  Future<void> crateApiInputAudioStartCapture() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiInputAudioStartCaptureConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputAudioStartCaptureConstMeta =>
      const TaskConstMeta(debugName: "audio_start_capture", argNames: []);

  @override
  Future<String> crateApiInputAudioStopCaptureAndTranscribe({
    required TranscriptionLanguage lang,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_transcription_language(lang, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_transcription_error,
        ),
        constMeta: kCrateApiInputAudioStopCaptureAndTranscribeConstMeta,
        argValues: [lang],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputAudioStopCaptureAndTranscribeConstMeta =>
      const TaskConstMeta(
        debugName: "audio_stop_capture_and_transcribe",
        argNames: ["lang"],
      );

  @override
  Future<BigInt> crateApiInputAudioStopCaptureLen() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiInputAudioStopCaptureLenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputAudioStopCaptureLenConstMeta =>
      const TaskConstMeta(debugName: "audio_stop_capture_len", argNames: []);

  @override
  Future<void> crateApiInputClearLastTranscription() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInputClearLastTranscriptionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputClearLastTranscriptionConstMeta =>
      const TaskConstMeta(debugName: "clear_last_transcription", argNames: []);

  @override
  Future<bool> crateApiCudaCudaAvailable() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCudaCudaAvailableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCudaCudaAvailableConstMeta =>
      const TaskConstMeta(debugName: "cuda_available", argNames: []);

  @override
  Future<int> crateApiWinprobeCurrentThreadId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWinprobeCurrentThreadIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWinprobeCurrentThreadIdConstMeta =>
      const TaskConstMeta(debugName: "current_thread_id", argNames: []);

  @override
  Future<void> crateApiOverlayDisableMenuMode({
    required String windowTitle,
    required bool hide_,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(windowTitle, serializer);
          sse_encode_bool(hide_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiOverlayDisableMenuModeConstMeta,
        argValues: [windowTitle, hide_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOverlayDisableMenuModeConstMeta =>
      const TaskConstMeta(
        debugName: "disable_menu_mode",
        argNames: ["windowTitle", "hide_"],
      );

  @override
  Future<void> crateApiOverlayEnableMenuMode({required String windowTitle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(windowTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiOverlayEnableMenuModeConstMeta,
        argValues: [windowTitle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOverlayEnableMenuModeConstMeta =>
      const TaskConstMeta(
        debugName: "enable_menu_mode",
        argNames: ["windowTitle"],
      );

  @override
  Future<bool> crateApiTranscriptionEngineIsReady() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTranscriptionEngineIsReadyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscriptionEngineIsReadyConstMeta =>
      const TaskConstMeta(debugName: "engine_is_ready", argNames: []);

  @override
  Future<TranscriptionLanguage> crateApiTranscriptionGetLanguage() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcription_language,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTranscriptionGetLanguageConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscriptionGetLanguageConstMeta =>
      const TaskConstMeta(debugName: "get_language", argNames: []);

  @override
  Future<String?> crateApiInputGetLastTranscription() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInputGetLastTranscriptionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputGetLastTranscriptionConstMeta =>
      const TaskConstMeta(debugName: "get_last_transcription", argNames: []);

  @override
  Future<bool> crateApiThemeGetTaskbarLightTheme() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiThemeGetTaskbarLightThemeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThemeGetTaskbarLightThemeConstMeta =>
      const TaskConstMeta(debugName: "get_taskbar_light_theme", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiOverlayHideOverlay({required String windowTitle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(windowTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiOverlayHideOverlayConstMeta,
        argValues: [windowTitle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOverlayHideOverlayConstMeta =>
      const TaskConstMeta(debugName: "hide_overlay", argNames: ["windowTitle"]);

  @override
  void crateApiSimpleInit() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitConstMeta =>
      const TaskConstMeta(debugName: "init", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiTranscriptionInitEngine({required bool fullVerify}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(fullVerify, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_transcription_error,
        ),
        constMeta: kCrateApiTranscriptionInitEngineConstMeta,
        argValues: [fullVerify],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscriptionInitEngineConstMeta =>
      const TaskConstMeta(debugName: "init_engine", argNames: ["fullVerify"]);

  @override
  Future<InjectionOutcomeDto> crateApiInputInjectText({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_injection_outcome_dto,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiInputInjectTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputInjectTextConstMeta =>
      const TaskConstMeta(debugName: "inject_text", argNames: ["text"]);

  @override
  Future<AppConfigDto> crateApiConfigLoadConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigLoadConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigLoadConfigConstMeta =>
      const TaskConstMeta(debugName: "load_config", argNames: []);

  @override
  Future<void> crateApiConfigSaveConfig({required AppConfigDto cfg}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_app_config_dto(cfg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_config_api_error,
        ),
        constMeta: kCrateApiConfigSaveConfigConstMeta,
        argValues: [cfg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigSaveConfigConstMeta =>
      const TaskConstMeta(debugName: "save_config", argNames: ["cfg"]);

  @override
  Future<void> crateApiTranscriptionSetLanguage({
    required TranscriptionLanguage lang,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_transcription_language(lang, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTranscriptionSetLanguageConstMeta,
        argValues: [lang],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscriptionSetLanguageConstMeta =>
      const TaskConstMeta(debugName: "set_language", argNames: ["lang"]);

  @override
  Future<void> crateApiOverlayShowOverlayNoActivate({
    required String windowTitle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(windowTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiOverlayShowOverlayNoActivateConstMeta,
        argValues: [windowTitle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOverlayShowOverlayNoActivateConstMeta =>
      const TaskConstMeta(
        debugName: "show_overlay_no_activate",
        argNames: ["windowTitle"],
      );

  @override
  Stream<HotkeyEventDto> crateApiInputStartHotkeyMonitor() {
    final sink = RustStreamSink<HotkeyEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_hotkey_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 26,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_input_error,
          ),
          constMeta: kCrateApiInputStartHotkeyMonitorConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiInputStartHotkeyMonitorConstMeta =>
      const TaskConstMeta(
        debugName: "start_hotkey_monitor",
        argNames: ["sink"],
      );

  @override
  Stream<UiStateDto> crateApiOrchestratorStartOrchestrator() {
    final sink = RustStreamSink<UiStateDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ui_state_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 27,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_input_error,
          ),
          constMeta: kCrateApiOrchestratorStartOrchestratorConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiOrchestratorStartOrchestratorConstMeta =>
      const TaskConstMeta(debugName: "start_orchestrator", argNames: ["sink"]);

  @override
  Future<void> crateApiInputStopHotkeyMonitor() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiInputStopHotkeyMonitorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInputStopHotkeyMonitorConstMeta =>
      const TaskConstMeta(debugName: "stop_hotkey_monitor", argNames: []);

  @override
  Future<void> crateApiOrchestratorStopOrchestrator() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiOrchestratorStopOrchestratorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOrchestratorStopOrchestratorConstMeta =>
      const TaskConstMeta(debugName: "stop_orchestrator", argNames: []);

  @override
  Future<void> crateApiThemeStopTaskbarThemeWatcher() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_input_error,
        ),
        constMeta: kCrateApiThemeStopTaskbarThemeWatcherConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThemeStopTaskbarThemeWatcherConstMeta =>
      const TaskConstMeta(
        debugName: "stop_taskbar_theme_watcher",
        argNames: [],
      );

  @override
  Future<String> crateApiTranscriptionTranscribePcm({
    required List<int> pcm,
    required TranscriptionLanguage lang,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_16_loose(pcm, serializer);
          sse_encode_transcription_language(lang, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_transcription_error,
        ),
        constMeta: kCrateApiTranscriptionTranscribePcmConstMeta,
        argValues: [pcm, lang],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscriptionTranscribePcmConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_pcm",
        argNames: ["pcm", "lang"],
      );

  @override
  Future<void> crateApiConfigUpdateLanguage({required String lang}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_config_api_error,
        ),
        constMeta: kCrateApiConfigUpdateLanguageConstMeta,
        argValues: [lang],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigUpdateLanguageConstMeta =>
      const TaskConstMeta(debugName: "update_language", argNames: ["lang"]);

  @override
  Future<void> crateApiConfigUpdateModelVerified({required bool verified}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(verified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_config_api_error,
        ),
        constMeta: kCrateApiConfigUpdateModelVerifiedConstMeta,
        argValues: [verified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigUpdateModelVerifiedConstMeta =>
      const TaskConstMeta(
        debugName: "update_model_verified",
        argNames: ["verified"],
      );

  @override
  Future<void> crateApiConfigUpdatePaused({required bool paused}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(paused, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_config_api_error,
        ),
        constMeta: kCrateApiConfigUpdatePausedConstMeta,
        argValues: [paused],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigUpdatePausedConstMeta =>
      const TaskConstMeta(debugName: "update_paused", argNames: ["paused"]);

  @override
  Future<void> crateApiConfigUpdateUiLanguage({required String lang}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_config_api_error,
        ),
        constMeta: kCrateApiConfigUpdateUiLanguageConstMeta,
        argValues: [lang],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigUpdateUiLanguageConstMeta =>
      const TaskConstMeta(debugName: "update_ui_language", argNames: ["lang"]);

  @override
  Future<String> crateApiTranscriptionVerifyModel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_transcription_error,
        ),
        constMeta: kCrateApiTranscriptionVerifyModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranscriptionVerifyModelConstMeta =>
      const TaskConstMeta(debugName: "verify_model", argNames: []);

  @override
  Stream<bool> crateApiThemeWatchTaskbarTheme() {
    final sink = RustStreamSink<bool>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_bool_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 37,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_input_error,
          ),
          constMeta: kCrateApiThemeWatchTaskbarThemeConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiThemeWatchTaskbarThemeConstMeta =>
      const TaskConstMeta(debugName: "watch_taskbar_theme", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<HotkeyEventDto> dco_decode_StreamSink_hotkey_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<UiStateDto> dco_decode_StreamSink_ui_state_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppConfigDto dco_decode_app_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AppConfigDto(
      language: dco_decode_String(arr[0]),
      paused: dco_decode_bool(arr[1]),
      logLevel: dco_decode_String(arr[2]),
      uiLanguage: dco_decode_String(arr[3]),
      modelVerified: dco_decode_bool(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppConfigDto dco_decode_box_autoadd_app_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_config_dto(raw);
  }

  @protected
  ConfigApiError dco_decode_config_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ConfigApiError_UnsupportedLanguage(dco_decode_String(raw[1]));
      case 1:
        return ConfigApiError_Persist(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  HotkeyEventDto dco_decode_hotkey_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return HotkeyEventDto_ComboPressed();
      case 1:
        return HotkeyEventDto_ComboReleased(
          holdMs: dco_decode_u_64(raw[1]),
          reason: dco_decode_release_reason_dto(raw[2]),
        );
      case 2:
        return HotkeyEventDto_SessionLocked();
      case 3:
        return HotkeyEventDto_SessionUnlocked();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InjectionOutcomeDto dco_decode_injection_outcome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return InjectionOutcomeDto.values[raw as int];
  }

  @protected
  InputError dco_decode_input_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return InputError_MonitorAlreadyRunning();
      case 1:
        return InputError_MonitorStartFailed(dco_decode_String(raw[1]));
      case 2:
        return InputError_MonitorNotRunning();
      case 3:
        return InputError_AudioNoDevice();
      case 4:
        return InputError_AudioInitFailed(dco_decode_String(raw[1]));
      case 5:
        return InputError_AudioNotPrewarmed();
      case 6:
        return InputError_InjectionFailed(dco_decode_String(raw[1]));
      case 7:
        return InputError_OrchestratorAlreadyRunning();
      case 8:
        return InputError_OrchestratorNotRunning();
      case 9:
        return InputError_OrchestratorStartFailed(dco_decode_String(raw[1]));
      case 10:
        return InputError_OverlayWindowNotFound(dco_decode_String(raw[1]));
      case 11:
        return InputError_OverlayStyleFailed(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ReleaseReasonDto dco_decode_release_reason_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReleaseReasonDto.values[raw as int];
  }

  @protected
  TranscriptionError dco_decode_transcription_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TranscriptionError_ModelMissing();
      case 1:
        return TranscriptionError_ModelCorrupt();
      case 2:
        return TranscriptionError_EngineLoadFailed(dco_decode_String(raw[1]));
      case 3:
        return TranscriptionError_Busy();
      case 4:
        return TranscriptionError_TranscribeFailed(dco_decode_String(raw[1]));
      case 5:
        return TranscriptionError_NotInitialized();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TranscriptionLanguage dco_decode_transcription_language(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TranscriptionLanguage.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiStateDto dco_decode_ui_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return UiStateDto_Listening();
      case 1:
        return UiStateDto_Transcribing();
      case 2:
        return UiStateDto_Injecting();
      case 3:
        return UiStateDto_Error(message: dco_decode_String(raw[1]));
      case 4:
        return UiStateDto_Hidden();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<HotkeyEventDto> sse_decode_StreamSink_hotkey_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<UiStateDto> sse_decode_StreamSink_ui_state_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppConfigDto sse_decode_app_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_language = sse_decode_String(deserializer);
    var var_paused = sse_decode_bool(deserializer);
    var var_logLevel = sse_decode_String(deserializer);
    var var_uiLanguage = sse_decode_String(deserializer);
    var var_modelVerified = sse_decode_bool(deserializer);
    return AppConfigDto(
      language: var_language,
      paused: var_paused,
      logLevel: var_logLevel,
      uiLanguage: var_uiLanguage,
      modelVerified: var_modelVerified,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppConfigDto sse_decode_box_autoadd_app_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_config_dto(deserializer));
  }

  @protected
  ConfigApiError sse_decode_config_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return ConfigApiError_UnsupportedLanguage(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return ConfigApiError_Persist(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  HotkeyEventDto sse_decode_hotkey_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return HotkeyEventDto_ComboPressed();
      case 1:
        var var_holdMs = sse_decode_u_64(deserializer);
        var var_reason = sse_decode_release_reason_dto(deserializer);
        return HotkeyEventDto_ComboReleased(
          holdMs: var_holdMs,
          reason: var_reason,
        );
      case 2:
        return HotkeyEventDto_SessionLocked();
      case 3:
        return HotkeyEventDto_SessionUnlocked();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InjectionOutcomeDto sse_decode_injection_outcome_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return InjectionOutcomeDto.values[inner];
  }

  @protected
  InputError sse_decode_input_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return InputError_MonitorAlreadyRunning();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return InputError_MonitorStartFailed(var_field0);
      case 2:
        return InputError_MonitorNotRunning();
      case 3:
        return InputError_AudioNoDevice();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return InputError_AudioInitFailed(var_field0);
      case 5:
        return InputError_AudioNotPrewarmed();
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return InputError_InjectionFailed(var_field0);
      case 7:
        return InputError_OrchestratorAlreadyRunning();
      case 8:
        return InputError_OrchestratorNotRunning();
      case 9:
        var var_field0 = sse_decode_String(deserializer);
        return InputError_OrchestratorStartFailed(var_field0);
      case 10:
        var var_field0 = sse_decode_String(deserializer);
        return InputError_OverlayWindowNotFound(var_field0);
      case 11:
        var var_field0 = sse_decode_String(deserializer);
        return InputError_OverlayStyleFailed(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReleaseReasonDto sse_decode_release_reason_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReleaseReasonDto.values[inner];
  }

  @protected
  TranscriptionError sse_decode_transcription_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return TranscriptionError_ModelMissing();
      case 1:
        return TranscriptionError_ModelCorrupt();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return TranscriptionError_EngineLoadFailed(var_field0);
      case 3:
        return TranscriptionError_Busy();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return TranscriptionError_TranscribeFailed(var_field0);
      case 5:
        return TranscriptionError_NotInitialized();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TranscriptionLanguage sse_decode_transcription_language(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TranscriptionLanguage.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UiStateDto sse_decode_ui_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return UiStateDto_Listening();
      case 1:
        return UiStateDto_Transcribing();
      case 2:
        return UiStateDto_Injecting();
      case 3:
        var var_message = sse_decode_String(deserializer);
        return UiStateDto_Error(message: var_message);
      case 4:
        return UiStateDto_Hidden();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_bool_Sse(
    RustStreamSink<bool> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_hotkey_event_dto_Sse(
    RustStreamSink<HotkeyEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_hotkey_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_ui_state_dto_Sse(
    RustStreamSink<UiStateDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_ui_state_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_config_dto(AppConfigDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.language, serializer);
    sse_encode_bool(self.paused, serializer);
    sse_encode_String(self.logLevel, serializer);
    sse_encode_String(self.uiLanguage, serializer);
    sse_encode_bool(self.modelVerified, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_config_dto(
    AppConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_config_dto(self, serializer);
  }

  @protected
  void sse_encode_config_api_error(
    ConfigApiError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ConfigApiError_UnsupportedLanguage(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case ConfigApiError_Persist(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_hotkey_event_dto(
    HotkeyEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case HotkeyEventDto_ComboPressed():
        sse_encode_i_32(0, serializer);
      case HotkeyEventDto_ComboReleased(
        holdMs: final holdMs,
        reason: final reason,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_64(holdMs, serializer);
        sse_encode_release_reason_dto(reason, serializer);
      case HotkeyEventDto_SessionLocked():
        sse_encode_i_32(2, serializer);
      case HotkeyEventDto_SessionUnlocked():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_injection_outcome_dto(
    InjectionOutcomeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_input_error(InputError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case InputError_MonitorAlreadyRunning():
        sse_encode_i_32(0, serializer);
      case InputError_MonitorStartFailed(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case InputError_MonitorNotRunning():
        sse_encode_i_32(2, serializer);
      case InputError_AudioNoDevice():
        sse_encode_i_32(3, serializer);
      case InputError_AudioInitFailed(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case InputError_AudioNotPrewarmed():
        sse_encode_i_32(5, serializer);
      case InputError_InjectionFailed(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case InputError_OrchestratorAlreadyRunning():
        sse_encode_i_32(7, serializer);
      case InputError_OrchestratorNotRunning():
        sse_encode_i_32(8, serializer);
      case InputError_OrchestratorStartFailed(field0: final field0):
        sse_encode_i_32(9, serializer);
        sse_encode_String(field0, serializer);
      case InputError_OverlayWindowNotFound(field0: final field0):
        sse_encode_i_32(10, serializer);
        sse_encode_String(field0, serializer);
      case InputError_OverlayStyleFailed(field0: final field0):
        sse_encode_i_32(11, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(
      self is Int16List ? self : Int16List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_release_reason_dto(
    ReleaseReasonDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transcription_error(
    TranscriptionError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TranscriptionError_ModelMissing():
        sse_encode_i_32(0, serializer);
      case TranscriptionError_ModelCorrupt():
        sse_encode_i_32(1, serializer);
      case TranscriptionError_EngineLoadFailed(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case TranscriptionError_Busy():
        sse_encode_i_32(3, serializer);
      case TranscriptionError_TranscribeFailed(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case TranscriptionError_NotInitialized():
        sse_encode_i_32(5, serializer);
    }
  }

  @protected
  void sse_encode_transcription_language(
    TranscriptionLanguage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_ui_state_dto(UiStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case UiStateDto_Listening():
        sse_encode_i_32(0, serializer);
      case UiStateDto_Transcribing():
        sse_encode_i_32(1, serializer);
      case UiStateDto_Injecting():
        sse_encode_i_32(2, serializer);
      case UiStateDto_Error(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
      case UiStateDto_Hidden():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
