// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/config.dart';
import 'api/cuda.dart';
import 'api/input.dart';
import 'api/instance.dart';
import 'api/orchestrator.dart';
import 'api/overlay.dart';
import 'api/simple.dart';
import 'api/theme.dart';
import 'api/transcription.dart';
import 'api/winprobe.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw);

  @protected
  RustStreamSink<HotkeyEventDto> dco_decode_StreamSink_hotkey_event_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<UiStateDto> dco_decode_StreamSink_ui_state_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppConfigDto dco_decode_app_config_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppConfigDto dco_decode_box_autoadd_app_config_dto(dynamic raw);

  @protected
  ConfigApiError dco_decode_config_api_error(dynamic raw);

  @protected
  HotkeyEventDto dco_decode_hotkey_event_dto(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InjectionOutcomeDto dco_decode_injection_outcome_dto(dynamic raw);

  @protected
  InputError dco_decode_input_error(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw);

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ReleaseReasonDto dco_decode_release_reason_dto(dynamic raw);

  @protected
  TranscriptionError dco_decode_transcription_error(dynamic raw);

  @protected
  TranscriptionLanguage dco_decode_transcription_language(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiStateDto dco_decode_ui_state_dto(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<HotkeyEventDto> sse_decode_StreamSink_hotkey_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UiStateDto> sse_decode_StreamSink_ui_state_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppConfigDto sse_decode_app_config_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppConfigDto sse_decode_box_autoadd_app_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConfigApiError sse_decode_config_api_error(SseDeserializer deserializer);

  @protected
  HotkeyEventDto sse_decode_hotkey_event_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InjectionOutcomeDto sse_decode_injection_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  InputError sse_decode_input_error(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer);

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ReleaseReasonDto sse_decode_release_reason_dto(SseDeserializer deserializer);

  @protected
  TranscriptionError sse_decode_transcription_error(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptionLanguage sse_decode_transcription_language(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiStateDto sse_decode_ui_state_dto(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bool_Sse(
    RustStreamSink<bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_hotkey_event_dto_Sse(
    RustStreamSink<HotkeyEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_state_dto_Sse(
    RustStreamSink<UiStateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_config_dto(AppConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_config_dto(
    AppConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_api_error(
    ConfigApiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hotkey_event_dto(
    HotkeyEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_injection_outcome_dto(
    InjectionOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_input_error(InputError self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_release_reason_dto(
    ReleaseReasonDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcription_error(
    TranscriptionError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcription_language(
    TranscriptionLanguage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_state_dto(UiStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
