// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'config.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Loads config.json (defaults when absent or invalid), applies it to
/// the runtime globals and returns it to Dart.
///
/// Design choice, per the plan: apply happens INSIDE load_config so
/// main.dart stays a single call with no duplicated mapping logic.
///
/// The merged result is also written back to disk. The write-back is
/// what creates the file with defaults on first launch (FR-10.AC-1)
/// and what heals a corrupt file into valid JSON (FR-10.AC-2). A
/// write-back failure is logged and swallowed on purpose, because a
/// read-only config directory must not abort startup.
Future<AppConfigDto> loadConfig() =>
    RustLib.instance.api.crateApiConfigLoadConfig();

/// Persists the given config atomically (save on change, FR-10).
Future<void> saveConfig({required AppConfigDto cfg}) =>
    RustLib.instance.api.crateApiConfigSaveConfig(cfg: cfg);

/// Validates the language, persists it into config.json and applies
/// it to the transcription global. The tray selector (Task 2, FR-07)
/// will call this. Validation happens before any file access, so an
/// unsupported value never touches the disk.
Future<void> updateLanguage({required String lang}) =>
    RustLib.instance.api.crateApiConfigUpdateLanguage(lang: lang);

/// Validates the UI language, persists it into config.json and leaves
/// the transcription language untouched (FR-13). The tray interface
/// language selector calls this. Validation happens before any file
/// access, so an unsupported value never touches the disk.
Future<void> updateUiLanguage({required String lang}) =>
    RustLib.instance.api.crateApiConfigUpdateUiLanguage(lang: lang);

/// Persists the FR-11 pause flag with a conservative merge (I-1): loads
/// the current config, mutates only `paused` and saves atomically, so a
/// pause/resume toggle can never clobber `model_verified` or any other
/// field written elsewhere (main.dart, the on-demand verify). This is
/// why the tray must call this instead of a wholesale `save_config`.
Future<void> updatePaused({required bool paused}) =>
    RustLib.instance.api.crateApiConfigUpdatePaused(paused: paused);

/// Persists the FR-09 first-run marker. main.dart sets it true after a
/// successful full-verify startup so later launches skip the expensive
/// SHA-256 check; the on-demand tray verification sets it false on
/// failure so the next launch re-verifies. Merges over the current
/// config so no other field is disturbed.
Future<void> updateModelVerified({required bool verified}) =>
    RustLib.instance.api.crateApiConfigUpdateModelVerified(verified: verified);

/// Mirror of [`AppConfig`] for the FRB scanner (only `api::` types
/// cross the bridge, same pattern as the input DTOs).
class AppConfigDto {
  final String language;
  final bool paused;
  final String logLevel;
  final String uiLanguage;
  final bool modelVerified;

  const AppConfigDto({
    required this.language,
    required this.paused,
    required this.logLevel,
    required this.uiLanguage,
    required this.modelVerified,
  });

  @override
  int get hashCode =>
      language.hashCode ^
      paused.hashCode ^
      logLevel.hashCode ^
      uiLanguage.hashCode ^
      modelVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfigDto &&
          runtimeType == other.runtimeType &&
          language == other.language &&
          paused == other.paused &&
          logLevel == other.logLevel &&
          uiLanguage == other.uiLanguage &&
          modelVerified == other.modelVerified;
}

@freezed
sealed class ConfigApiError with _$ConfigApiError implements FrbException {
  const ConfigApiError._();

  const factory ConfigApiError.unsupportedLanguage(String field0) =
      ConfigApiError_UnsupportedLanguage;
  const factory ConfigApiError.persist(String field0) = ConfigApiError_Persist;
}
