// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'transcription.dart';
part 'input.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `current_default_input_name`, `device_watch_tick`, `lock_audio`, `lock_monitor`, `start_device_watcher`, `with_audio`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MonitorState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

/// Start the global Ctrl+Win monitor and stream its events to Dart.
///
/// Fails with [`InputError::MonitorAlreadyRunning`] if a monitor is
/// already active (one low-level hook per process).
Stream<HotkeyEventDto> startHotkeyMonitor() =>
    RustLib.instance.api.crateApiInputStartHotkeyMonitor();

/// Stop the hotkey monitor started by [`start_hotkey_monitor`].
Future<void> stopHotkeyMonitor() =>
    RustLib.instance.api.crateApiInputStopHotkeyMonitor();

/// Open and start the microphone stream so capture starts are
/// instantaneous (NFR-02). Idempotent: a second call reuses the
/// existing stream.
Future<void> audioPrewarm() => RustLib.instance.api.crateApiInputAudioPrewarm();

/// Begin accumulating microphone samples (FR-02).
Future<void> audioStartCapture() =>
    RustLib.instance.api.crateApiInputAudioStartCapture();

/// Stop accumulating and return only the PCM length in samples (UI
/// metric). The PCM itself never crosses to Dart in the normal flow.
Future<BigInt> audioStopCaptureLen() =>
    RustLib.instance.api.crateApiInputAudioStopCaptureLen();

/// Full-pipeline preview (first real dictation): stop the capture and
/// feed the PCM straight into the resident Whisper engine, all on the
/// Rust side. Only the transcribed text crosses to Dart.
///
/// Error mapping caveat: the mandated signature returns
/// [`TranscriptionError`], so a missing `audio_prewarm` surfaces as
/// [`TranscriptionError::TranscribeFailed`] with an explanatory
/// message (there is no audio variant in that enum by design).
Future<String> audioStopCaptureAndTranscribe({
  required TranscriptionLanguage lang,
}) =>
    RustLib.instance.api.crateApiInputAudioStopCaptureAndTranscribe(lang: lang);

/// Pastes `text` into the currently focused window via the full FR-05
/// sequence (see [`crate::inject::inject`]) - wait for the physical
/// modifiers to be released, snapshot the clipboard, paste, restore.
///
/// The text is stored as the last-transcription backup BEFORE the
/// paste is attempted, so [`get_last_transcription`] can hand it back
/// even when the injection itself fails (FR-05 fallback).
///
/// NFR-12 - the text content is never logged, only its length.
Future<InjectionOutcomeDto> injectText({required String text}) =>
    RustLib.instance.api.crateApiInputInjectText(text: text);

/// Returns the last transcription kept as the FR-05 in-memory backup,
/// if any (stored by [`inject_text`]; never logged, NFR-12).
Future<String?> getLastTranscription() =>
    RustLib.instance.api.crateApiInputGetLastTranscription();

/// Drops the in-memory last-transcription backup (TD-008, NFR-12
/// hygiene). Wired into the ordered shutdown path: the tray Quit item
/// calls this right before the process exits.
Future<void> clearLastTranscription() =>
    RustLib.instance.api.crateApiInputClearLastTranscription();

@freezed
sealed class HotkeyEventDto with _$HotkeyEventDto {
  const HotkeyEventDto._();

  /// The Ctrl+Win combo just became active.
  const factory HotkeyEventDto.comboPressed() = HotkeyEventDto_ComboPressed;

  /// The Ctrl+Win combo just ended.
  const factory HotkeyEventDto.comboReleased({
    /// How long the combo was held, in milliseconds.
    required BigInt holdMs,

    /// What ended the combo.
    required ReleaseReasonDto reason,
  }) = HotkeyEventDto_ComboReleased;

  /// The interactive session was locked.
  const factory HotkeyEventDto.sessionLocked() = HotkeyEventDto_SessionLocked;

  /// The interactive session was unlocked.
  const factory HotkeyEventDto.sessionUnlocked() =
      HotkeyEventDto_SessionUnlocked;
}

/// Injection outcome, as exposed to Dart (mirror of
/// [`crate::inject::InjectionOutcome`], kept separate so the FRB
/// scanner only walks `api::` types).
enum InjectionOutcomeDto {
  /// Text pasted and the previous clipboard contents were restored.
  pasted,

  /// Text pasted but restoring the previous clipboard failed. Not
  /// fatal - the transcription reached the target app.
  pastedRestoreFailed,
}

@freezed
sealed class InputError with _$InputError implements FrbException {
  const InputError._();

  const factory InputError.monitorAlreadyRunning() =
      InputError_MonitorAlreadyRunning;
  const factory InputError.monitorStartFailed(String field0) =
      InputError_MonitorStartFailed;
  const factory InputError.monitorNotRunning() = InputError_MonitorNotRunning;
  const factory InputError.audioNoDevice() = InputError_AudioNoDevice;
  const factory InputError.audioInitFailed(String field0) =
      InputError_AudioInitFailed;
  const factory InputError.audioNotPrewarmed() = InputError_AudioNotPrewarmed;
  const factory InputError.injectionFailed(String field0) =
      InputError_InjectionFailed;
  const factory InputError.orchestratorAlreadyRunning() =
      InputError_OrchestratorAlreadyRunning;
  const factory InputError.orchestratorNotRunning() =
      InputError_OrchestratorNotRunning;
  const factory InputError.orchestratorStartFailed(String field0) =
      InputError_OrchestratorStartFailed;
  const factory InputError.overlayWindowNotFound(String field0) =
      InputError_OverlayWindowNotFound;
  const factory InputError.overlayStyleFailed(String field0) =
      InputError_OverlayStyleFailed;
}

/// What ended a combo, as exposed to Dart (mirror of
/// [`crate::hotkey::ReleaseReason`], kept separate so the FRB scanner
/// only walks `api::` types).
enum ReleaseReasonDto {
  /// Ctrl or Win was lifted normally.
  keyLifted,

  /// A third key was pressed while the combo was held.
  otherKeyPressed,

  /// The interactive session was locked (e.g. Win+L).
  sessionLocked,
}
