// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Attempts to become the single instance for this user session.
///
/// Returns `true` if THIS process is the first (and only) instance and
/// may continue starting up. Returns `false` if another instance
/// already owns the guard, in which case the caller MUST exit without
/// installing the keyboard hook / audio / engine (see TD-011).
///
/// Idempotent within a process: the handle is created at most once and
/// cached in [`INSTANCE_MUTEX`]. A second call in the same process
/// returns `true` (this process already IS the instance) without
/// creating another handle.
Future<bool> acquireSingleInstance() =>
    RustLib.instance.api.crateApiInstanceAcquireSingleInstance();
