// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'input.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'orchestrator.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `lock_orchestrator`, `production_deps`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OrchestratorState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`

/// Start the resident dictation orchestrator and stream overlay states
/// to Dart. Pre-warms (or reuses) the process-wide audio capture and
/// starts the hotkey monitor internally; call `init_engine` before the
/// first dictation or the cycle will surface an Error state.
Stream<UiStateDto> startOrchestrator() =>
    RustLib.instance.api.crateApiOrchestratorStartOrchestrator();

/// Stop the orchestrator started by [`start_orchestrator`].
Future<void> stopOrchestrator() =>
    RustLib.instance.api.crateApiOrchestratorStopOrchestrator();

@freezed
sealed class UiStateDto with _$UiStateDto {
  const UiStateDto._();

  /// Recording is active (combo held).
  const factory UiStateDto.listening() = UiStateDto_Listening;

  /// Audio was sent to the engine; waiting for text.
  const factory UiStateDto.transcribing() = UiStateDto_Transcribing;

  /// Text is being pasted into the focused control.
  const factory UiStateDto.injecting() = UiStateDto_Injecting;

  /// A cycle failed; the message goes to the overlay and the log.
  const factory UiStateDto.error({required String message}) = UiStateDto_Error;

  /// No cycle in flight; the overlay hides itself.
  const factory UiStateDto.hidden() = UiStateDto_Hidden;
}
