// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'input.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `find_overlay_window_of_class`, `find_overlay_window`, `overlay_ex_style_bits`

/// Applies the FR-03 window styles to the (already created) Flutter
/// overlay window identified by `window_title`:
///
/// - `WS_EX_LAYERED | WS_EX_TRANSPARENT`: clicks pass through to the
///   window underneath (FR-03.AC-2).
/// - `WS_EX_NOACTIVATE`: the window never takes focus (FR-03.AC-3).
/// - `WS_EX_TOPMOST` + `SetWindowPos(HWND_TOPMOST)`: always on top.
/// - `WS_EX_TOOLWINDOW`: hidden from taskbar and Alt+Tab.
/// - `SetLayeredWindowAttributes(alpha = 255)`: REQUIRED - a layered
///   window renders nothing at all until its transparency is set once;
///   255 keeps the Flutter content fully opaque (the visual
///   semi-transparency comes from Flutter's own alpha colors).
///
/// Call it once at startup, after the window exists and its title was
/// set, and before the first show.
Future<void> applyOverlayStyles({required String windowTitle}) => RustLib
    .instance
    .api
    .crateApiOverlayApplyOverlayStyles(windowTitle: windowTitle);

/// Shows the overlay WITHOUT activating it (`SW_SHOWNOACTIVATE`), so
/// the focused app keeps its focus and caret (FR-03.AC-3).
Future<void> showOverlayNoActivate({required String windowTitle}) => RustLib
    .instance
    .api
    .crateApiOverlayShowOverlayNoActivate(windowTitle: windowTitle);

/// Hides the overlay (`SW_HIDE`). Focus is unaffected: a NOACTIVATE
/// window never had it.
Future<void> hideOverlay({required String windowTitle}) =>
    RustLib.instance.api.crateApiOverlayHideOverlay(windowTitle: windowTitle);

/// Makes the overlay window able to host the tray context menu.
///
/// The tray plugin owns its popup menu from the Flutter main window and
/// requires SetForegroundWindow to succeed. Our overlay carries
/// WS_EX_NOACTIVATE, which Windows honors by DENYING SetForegroundWindow,
/// so TrackPopupMenu would show nothing. This temporarily strips the
/// no-activate and click-through bits and brings the window to the
/// foreground. When idle the overlay renders a transparent, empty frame,
/// so nothing visible flashes. Pair every call with `disable_menu_mode`.
Future<void> enableMenuMode({required String windowTitle}) => RustLib
    .instance
    .api
    .crateApiOverlayEnableMenuMode(windowTitle: windowTitle);

/// Restores the overlay FR-03 styles after the tray menu closes.
/// `hide` is true when the dictation phase is idle so the window goes
/// back to SW_HIDE; during an active dictation the caller keeps it shown.
Future<void> disableMenuMode({
  required String windowTitle,
  required bool hide_,
}) => RustLib.instance.api.crateApiOverlayDisableMenuMode(
  windowTitle: windowTitle,
  hide_: hide_,
);
