// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'input.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WatcherState`

/// Taskbar theme right now. Falls back to dark (false) when the
/// registry value is unreadable - dark is the Windows 11 default.
Future<bool> getTaskbarLightTheme() =>
    RustLib.instance.api.crateApiThemeGetTaskbarLightTheme();

/// Streams taskbar theme changes (true = light) to Dart. One watcher
/// per process; mirrors the hotkey monitor start/stop contract.
Stream<bool> watchTaskbarTheme() =>
    RustLib.instance.api.crateApiThemeWatchTaskbarTheme();

/// Stops the theme watcher (symmetry / test hygiene; the app itself
/// keeps it for the process lifetime).
Future<void> stopTaskbarThemeWatcher() =>
    RustLib.instance.api.crateApiThemeStopTaskbarThemeWatcher();
