// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'transcription.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `verify_model_in`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Locates the model, optionally verifies the full hash, and loads the
/// engine. Returns the path of the model in use.
///
/// `full_verify`: true only on first launch (FR-09). Idempotent: if the
/// engine is already loaded it returns the original path without reloading
/// (FR-04.AC-4: the model is loaded exactly once). CAVEAT: in that case a
/// requested `full_verify` is NOT performed (a warning is logged); the
/// on-demand verification path needs a separate `verify_model()` API —
/// implemented by `verifyModel`.
Future<String> initEngine({required bool fullVerify}) => RustLib.instance.api
    .crateApiTranscriptionInitEngine(fullVerify: fullVerify);

/// On-demand full integrity check (FR-09.AC-2, closes TD-004). Locates
/// the model and verifies its SHA-256 ALWAYS, independent of whether the
/// engine is loaded, and WITHOUT reloading it. Returns the verified
/// model path on success. The tray "Verify model" item calls this; a
/// failure maps to ModelMissing/ModelCorrupt exactly like startup, so
/// the app can surface the reinstall guidance.
Future<String> verifyModel() =>
    RustLib.instance.api.crateApiTranscriptionVerifyModel();

/// Transcribes PCM 16-bit 16 kHz mono. Returns trimmed text.
Future<String> transcribePcm({
  required List<int> pcm,
  required TranscriptionLanguage lang,
}) => RustLib.instance.api.crateApiTranscriptionTranscribePcm(
  pcm: pcm,
  lang: lang,
);

/// True if the engine was already initialized in this process.
Future<bool> engineIsReady() =>
    RustLib.instance.api.crateApiTranscriptionEngineIsReady();

/// Sets the global language used for subsequent transcriptions.
Future<void> setLanguage({required TranscriptionLanguage lang}) =>
    RustLib.instance.api.crateApiTranscriptionSetLanguage(lang: lang);

/// Current global transcription language (default Spanish).
Future<TranscriptionLanguage> getLanguage() =>
    RustLib.instance.api.crateApiTranscriptionGetLanguage();

@freezed
sealed class TranscriptionError
    with _$TranscriptionError
    implements FrbException {
  const TranscriptionError._();

  const factory TranscriptionError.modelMissing() =
      TranscriptionError_ModelMissing;
  const factory TranscriptionError.modelCorrupt() =
      TranscriptionError_ModelCorrupt;
  const factory TranscriptionError.engineLoadFailed(String field0) =
      TranscriptionError_EngineLoadFailed;
  const factory TranscriptionError.busy() = TranscriptionError_Busy;
  const factory TranscriptionError.transcribeFailed(String field0) =
      TranscriptionError_TranscribeFailed;
  const factory TranscriptionError.notInitialized() =
      TranscriptionError_NotInitialized;
}

enum TranscriptionLanguage { es, en }
